package com.antonov.vlmart.model.enums;

import lombok.Getter;

public enum NOTIFY_TYPE {
    WELCOME(NOTIFY_STYLE.PRIMARY),
    FIRST_LIKE(NOTIFY_STYLE.SUCCESS),
    DISLIKE_ABSENT_POSITIONS(NOTIFY_STYLE.DANGER),
    SUPPLY_NEEDED(NOTIFY_STYLE.DANGER),
    ALL_SUPPLY_NEEDED(NOTIFY_STYLE.DANGER),
    SUPPLY_PRICE(NOTIFY_STYLE.PRIMARY),
    LOW_STOCK_IN_SHOP(NOTIFY_STYLE.DANGER),
    LONG_CASH_QUEUE(NOTIFY_STYLE.DANGER),
    SUPPLY_UNLOAD_NEEDED(NOTIFY_STYLE.WARNING),
    ALL_LOW_STOCK_IN_SHOP(NOTIFY_STYLE.DANGER),
    FIRST_BUYER_IN_CASH(NOTIFY_STYLE.WARNING),
    CAN_BUY_CAHIER(NOTIFY_STYLE.PRIMARY),
    CAN_BUY_SHELVER(NOTIFY_STYLE.PRIMARY),
    CAN_BUY_LOADER(NOTIFY_STYLE.PRIMARY);

    @Getter
    private final NOTIFY_STYLE style;

    NOTIFY_TYPE(NOTIFY_STYLE style) {
        this.style = style;
    }
}
